### ISSUE TITLE
Handling export choice between scaled or integrated intensities

### ISSUE THREAD

**Issue by jbeilstenedmands** [ccp4/DUI#102]
I have been thinking about how to improve the exporting, as I saw a user not click the "output scaled intensities" button upon export for exporting scaled data, as it is not on by default.

My thoughts for improvement are have two tick boxes in the panel, 'export integrated (unscaled) intensities' and 'export scaled intensities', which are mutually exclusive (i.e. clicking one would remove a tick from the other). To determine which one is initially on, one could use a simple inspection of the current reflection table, to see if it has the column 'inverse_scale_factor', or it might be worth adding an extra 'scaled' flag to the reflection table which could be set at the end of scaling.

This could then also be used to determine the choice of name for the mtz, to address #101

**Comment by dagewa** [comment]
I like the idea of automatically choosing the default, however there might be circumstances where exporting the integrated intensities alongside the scaled intensities is useful. I would have two tick boxes and set the default as described, but not make them mutually exclusive.

**Comment by jbeilstenedmands** [comment]
This is a good point, for example for mmcif format we can export all intensity types together (although for mtz export using the command line, if I use intensity=profile+sum+scale it seems that just scaled intensities are output, but I'm not sure what dials.export should want to do in this situation)

**Comment by dagewa** [comment]
I think MTZ export should allow export of all three, any two, or just one intensity column as chosen by the user (with sensible column names)

**Comment by ndevenish** [comment]
Adding this to milestone as related to #101

**Comment by dagewa** [comment]
The basic problem appears fixed, though the ideas in comments are not done. Close enough though.
