### ISSUE TITLE
Button text cropped

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#107]
![screenshot 2019-01-16 09 48 16](https://user-images.githubusercontent.com/11502083/51240749-4b325000-1974-11e9-9b81-6d6ed4d5ac50.png)

**Comment by dagewa** [comment]
this is with DUI release 2019.1, testing inclusion in CCP4

**Comment by dagewa** [comment]
Title changed as it also affects Linux, and as reported by @graeme-winter, Macs.

**Comment by dagewa** [comment]
There is more than one button where this is the case, so the fix needs to be general

**Comment by dagewa** [comment]
This appears to be fixed in the PySide2 version.

**Comment by ndevenish** [comment]
Ah, missed this one off the list!
