### ISSUE TITLE
Report maths does not display properly on Windows

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#109]
![screenshot 2019-01-16 10 38 01](https://user-images.githubusercontent.com/11502083/51243590-db739380-197a-11e9-8a2f-ba99ccdb1aa7.png)

**Comment by ndevenish** [comment]
This is still a problem

**Comment by dagewa** [comment]
Apparently fixed now in DUI 2021.11.1, in CCP4 8.0
