### ISSUE TITLE
Inappropriate scientific display in refinement list

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#11]
After running the index step and the automatic refine, the table it displays shows even three-digit numbers (e.g. column C and B2) in scientific form, when clearly the number fits. This ends up obfuscating the number somewhat.

![image](https://user-images.githubusercontent.com/529963/26882770-37606c70-4b93-11e7-8eed-5321fda45dc7.png)

**Comment by dagewa** [comment]
@luisodls Easy fix. Think you have done it already? Please close if so

**Comment by luisodls** [comment]
yes ... done already
