### ISSUE TITLE
Possible icon size issues on retina mac display?

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#110]
Switched to laptop screen, pretty sure nothing else had changed since earlier when it worked:

![image](https://user-images.githubusercontent.com/529963/51281373-1b1d9800-19da-11e9-80bc-faed6c41c8ac.png)

Still need to cross-check this but probably worth trying on e.g. @dagewa's retina ubuntu monitor.

**Comment by dagewa** [comment]
Looks okay in 2019.1 from CCP4 trial update 068
![untitled](https://user-images.githubusercontent.com/11502083/51308217-864a8700-1a39-11e9-918d-0da1ff31712b.png)

**Comment by rjgildea** [comment]
Apart from the non-circular magnifying glass icons...

**Comment by ndevenish** [comment]
I've.... been told that's deliberate.

**Comment by dagewa** [comment]
@ndevenish do you still get the ugly display on a Mac HiDPI screen?

**Comment by ndevenish** [comment]
If still an issue with fusion will pick up separately
