### ISSUE TITLE
"Global Threshold" on spot finding cannot go over 99.9

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#111]
This makes it difficult on e.g. CCD

**Comment by graeme-winter** [comment]
Seriously?

**Comment by ndevenish** [comment]
Should also take the opportunity to survey anything else that this might affect rather than fixing just this one instance.

For a while I've wanted to refactor into a "give me a UI widget for this `<phil scope>, "phil.path"`, rather than doing it locally and manually for every single control. You should do this as long term it'll make your life easier and more consistent.
