### ISSUE TITLE
Count summary e.g. strong/indexed/integrated counts not showing

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#112]
e.g.
![image](https://user-images.githubusercontent.com/529963/51476315-def98700-1d8d-11e9-9846-f2d9d7c3e3dc.png)

I tried this on my mac and it appears to be working, so this might be a windows only problem? I know it sounds strange, but all the machines we used for the workshop exhibited the same problem, so it's not something on just my computer.

**Comment by luisodls** [comment]
Done a while ago
