### ISSUE TITLE
Image viewer window too small on mac

### ISSUE THREAD

**Issue by rjgildea** [ccp4/DUI#123]
<img width="1135" alt="Screenshot 2019-08-05 at 10 48 05" src="https://user-images.githubusercontent.com/2810624/62455575-9f651c00-b76e-11e9-88e3-117692020192.png">

**Comment by ndevenish** [comment]
Part of this at least looks like the long-term spacing/border issue on the top bar

**Comment by luisodls** [comment]
Since the info panel was moved to a new tab I am closing this issue.
Feel free to reopen if you consider.
