### ISSUE TITLE
Provide list of output files for i2

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#129]
In discussion with ccp4i2 developers, it has become clear that it would be useful for dui to create a list of output files (exported MTZs and their associated `dials.export.log` files) so that i2 can capture the correct files for downstream tasks.

At the moment, a DUI session could result in any number of MTZ files with arbitrary filenames. It would make things easier for i2 if every export job in DUI added a record to a file with a known name (say `dui_files/output.json`). If DUI overwrites a previously created file then the relevant record should be replaced in `output.json` rather than a new one appended.

The records in `output.json` could also include other information, such as whether an MTZ is scaled and merged, which means that i2 would not have to figure this out itself for each output file.

**Comment by luisodls** [comment]
Done with new manifest file
