### ISSUE TITLE
Parameter search usability

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#130]
- [ ] In the search parameters box the search text "Type search here" needs to be selected and deleted. In QT you can specify kind of hidden text for this purpose.

- [ ] The original DUI parameter search would filter the parameters so you only saw those that matched the search text. However, the version in CCP4 only highlights the matching parameters which is less convenient because you still have to scroll through for a while to find the parameter of interest.

**Comment by dagewa** [comment]
This remains an annoying usability issue at the DLS/CCP4 workshop

**Comment by ndevenish** [comment]
Also in Bangkok 2020: Is it worth splitting these up - the first seems like a very simple fix?

**Comment by dagewa** [comment]
I couldn't find a simple widget example for this, which was surprising, but the work in https://github.com/ccp4/DUI/tree/search-text shows how to get proper search behaviour. What it needs is a couple of extra buttons (next/previous) alongside the search box and maybe an indicator of the number of matches. Something like the Chrome search box:
![Screenshot from 2020-03-07 13-37-00](https://user-images.githubusercontent.com/11502083/76144560-a6903780-6079-11ea-859a-51606b19ee9d.png)

**Comment by dagewa** [comment]
This works with a "Find next" button now. It isn't perfect but is a big improvement.
