### ISSUE TITLE
Scrolling advanced with mouse wheel changes fields

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#142]
DUI 2012.1: Encountered by several students; they looked at the advanced tab, scrolled around a bit, ran the stage and then it failed because they had accidentally changed something:
![output](https://user-images.githubusercontent.com/529963/73046435-b0ccec80-3ea4-11ea-9514-bf7182bfa2a9.gif)

**Comment by dagewa** [comment]
Yes! I've had this. It's incredibly annoying. I guess the solution should be that widgets only get focus when the user clicks on them, not on mouse-over?

**Comment by ndevenish** [comment]
This possibly helpful: https://forum.qt.io/topic/50189/how-to-lock-combobox-scrolling-while-scrolling-in-scrollarea/5

**Comment by dagewa** [comment]
@luisodls you started looking at this... does this link help?

**Comment by dagewa** [comment]
This appears to be fixed now, at least on Linux. @luisodls @luisolafg did you work on this? If it is fixed can you please close the issue?

**Comment by luisodls** [comment]
Yes I did, closing now
