### ISSUE TITLE
d_min on integrate: Clicking up then down fails to run

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#143]
Dui 2012.1:
On integrate simple page. `d_min` says `None`:
![image](https://user-images.githubusercontent.com/529963/73116056-bb4dbb80-3f62-11ea-98ab-4f28a786ea49.png)
Click up:
![image](https://user-images.githubusercontent.com/529963/73116062-cdc7f500-3f62-11ea-99d3-e49bcbbfd7d9.png)
Click down:
![image](https://user-images.githubusercontent.com/529963/73116063-d5879980-3f62-11ea-8d9e-7b7afb667d9d.png)
Click run. Integrate fails because `0` gets passed through as `d_min`.
```
prediction {
  d_min = 0
}
...
Sorry: Prediction at d_min of 0.0 is not possible with wavelength 1.23985
```

**Comment by dagewa** [comment]
I've been looking at this. I can see why it doesn't work and how to catch the case where we'd like to reset the `d_min` parameter. However I can't see any way to actually remove `prediction.d_min` from the parameters after it has been set once. @luisodls how are you supposed to reset a single parameter from within the `IntegrateSimplerParamTab` class?

**Comment by dagewa** [comment]
Found it, but see commit message.
