### ISSUE TITLE
Cannot type in integrate/scale d_min boxes

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#144]
Typing into the integrate/scale `d_min` boxes is extremely difficult... you basically need to select and replace each character individually 
![Jan-25-2020 11-59-09](https://user-images.githubusercontent.com/529963/73116527-43838f00-3f6a-11ea-8670-36a38dd08ecf.gif)

Dui 2019.12

**Comment by dagewa** [comment]
Thanks for the enlightening .gif! (I'm going to have to ask you how you make these...)

**Comment by ndevenish** [comment]
https://giphy.com/apps/giphycapture and https://github.com/keycastr/keycastr (and imagemagick to recompress), though obviously those apps won't help you on linux. Tried to find one for linux that worked on the diamond machines but just ran over nx rather than shave that yak ^^
