### ISSUE TITLE
Ubuntu 19.10: No search highlighting

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#145]
Users trying to search found that there was no search highlighting... this was on the CCP4 preview on ubuntu 19.10, so possibly some weird corner case - would need to test on precise OS to see if reproducible:

![Advanced copy](https://user-images.githubusercontent.com/529963/73116609-be997500-3f6b-11ea-932e-ea51396f5e20.jpg)

Ideally we'd have search jumping/filtering because it really is annoying to have to scroll through anyway e.g. https://github.com/ccp4/DUI/issues/130

**Comment by dagewa** [comment]
Suspect fixed.
