### ISSUE TITLE
Exporting is allowed before integrate but fails

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#146]
Find Spots -> Index -> Export...

```
  File "/dls_sw/apps/ccp4/7.1.000-preview-5/ccp4-7.1/lib/py2/site-packages/dials/util/filter_reflections.py", line 113, in filter_reflection_table
    assert "intensity.prf.value" in reflection_table
AssertionError
```

**Comment by dagewa** [comment]
I'm tempted to call this a DIALS error. Running `dials.export` before integrate is okay for some modes like `format=mosflm`, but not for `format=mtz`. Perhaps `dials.export` should fail gracefully here and DUI just report that.

**Comment by ndevenish** [comment]
I think you are right but it's two part;
- I don't think DUI supports anything except MTZ export at the moment? If that's the case then it's never valid to export before integration
- DIALS should do something more graceful than stacktrace. Made https://github.com/dials/dials/issues/1113
