### ISSUE TITLE
Initial "Next step" button should be "Import", not "Run"

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#15]
Opening DUI from nothing gives the 'Next stage' button as 'Run' when it should probably be import. This means you have to click the toolbar import button explicitly.

![dials_ui](https://user-images.githubusercontent.com/529963/27136677-d4d5acec-5113-11e7-897c-fb52d8631796.png)

Clicking 'import' and then cancel changes the button to say 'Import' as it probably should anyway, but clicking doesn't actually do anything (perhaps the first click should open the file dialog? It's slightly non-obvious that you have to click the import icon *then* the text button)

**Comment by luisodls** [comment]
not worth fixing in this version
