### ISSUE TITLE
python/terminal complains after masking

### ISSUE THREAD

**Issue by luisodls** [ccp4/DUI#162]
When using the mask tool, DUI runs the masking just fine, but immediately after DUI runs the masking tool, if the users click anywhere in the image, the console complains with the following message:

```
Traceback (most recent call last):
  File "/scratch/ccp4-7.1/lib/py2/site-packages/dui/outputs_n_viewers/img_viewer.py", line 294, in mouseReleaseEvent
    if mask_item:
UnboundLocalError: local variable 'mask_item' referenced before assignment
```

**Comment by dagewa** [comment]
Thanks, confirmed. The fix is trivial, will commit shortly
