### ISSUE TITLE
No time

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#163]
```
Traceback (most recent call last):
  File "/home/fcx32934/sw/ccp4-7.1/lib/py2/site-packages/dui/m_idials_gui.py", line 140, in run
    time.sleep(0.25)
AttributeError: 'NoneType' object has no attribute 'sleep'
```

**Comment by dagewa** [comment]
It's not clear how this is possible. It isn't easily reproducible

**Comment by ndevenish** [comment]
>  It isn't easily reproducible

did it happen more than once? I'm tempted to write it off as a ccp4/python VM glitch or something, I can't see anything that would cause this either.

**Comment by dagewa** [comment]
Happy to put it down to a glitch
