### ISSUE TITLE
Image zoom speed slow

### ISSUE THREAD

**Issue by neil-i03** [ccp4/DUI#17]
Scrolling from full image to view 2-3 spots is slow due to small step size, could we increase the default step or have it as a customisable feature?

**Comment by dagewa** [comment]
@luisodls can you test this? It seems fast to me. Perhaps it is slow for certain images?

**Comment by dagewa** [comment]
Checking in another year later... ;-) I think this could be closed, but I'd like @luisodls to check if he is happy with the current behaviour first.
