### ISSUE TITLE
Easily output merged MTZ

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#179]
DUI does not make it very easy to get a merged MTZ, so CCP4 users are having to run an Aimless "only merge" job after getting `scaled.mtz` from DUI for downstream steps. A simple solution would be to add another checkbox to the export task to perform merging if scaled intensities are selected .

**Comment by jbeilstenedmands** [comment]
Another option would be checkboxes for the dials.scale job, as both the unmerged and merged mtz files can be generated there too.

**Comment by dagewa** [comment]
This is true, but the DUI workflow kind of pushes the user towards an explicit export. Whether that is right or not is debatable...
