### ISSUE TITLE
Indexing - add max_cell, space_group and unit_cell

### ISSUE THREAD

**Issue by neil-i03** [ccp4/DUI#18]
The indexing tab has a simple and advanced settings page, but the parameters on simple seem an odd choice. I'd say resolution, maybe spot I/sigI or known cell/SG would be better choices than indexing algorithm.

**Comment by neil-i03** [comment]
Similar issue for the integrate tab, resolution probably a more pertinent choice for the simple tab rather than the choice of algorithm.

**Comment by dagewa** [comment]
`d_min` is now in integrate's simple tab, Indexing method does seem appropriate. Adding `max_cell`, `space_group` and `unit_cell` is important

**Comment by dagewa** [comment]
I changed the title to be more direct about what is needed. This came up a few times during the workshop here.

**Comment by dagewa** [comment]
Thanks, I can confirm the fix :-)
![Screenshot from 2020-02-24 15-49-17](https://user-images.githubusercontent.com/11502083/75167433-41ede800-571d-11ea-9f1e-0085d5d72a85.png)
