### ISSUE TITLE
Import selection unintuitively groups unselected files

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#19]
.. as in the actual images selected aren't necessarily reflected in the import. e.g. if you only select:

    X4_0001.cbf
    X4_0002.cbf

It gives the filter:

    X4_000#.cbf

Which resolves to nine images. Probably a less directly useful example (given less common split experiment data), but selecting the two files:

    X4_0001.cbf
    X4_0090.cbf

Gives the filter:

    X4_00##.cbf

Importing 90 files, when only two were selected!

**Comment by luisodls** [comment]
fixed already
