### ISSUE TITLE
No way to find out previous settings

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#24]
If I run a stage and choose some custom advanced settings, then go back and run it again, there is no way to tell what settings I chose (and thus the difference) between the two stages. 

e.g. you could get to the end of your analysis, integration, and come up with two separate results where one is much better, and you want to go back and see what settings you used (in order to use those settings in other analyses).

Related to #23, in that to re-run a stage you have to select the parent of the stage - in a tree situation with potentially many branches, selecting the parent gives no context for which child you want to change.

**Comment by luisodls** [comment]
fixed since the new design of the tree is entirely different
