### ISSUE TITLE
Explanation of parameters

### ISSUE THREAD

**Issue by anna-vmxm** [ccp4/DUI#27]
In the simple and advanced tabs of each process to run there are a number of parameters that can be edited.  It may be useful to include more information about what each of these parameters is doing to help the user decide what would be good to change.  This could be a pop up that appears when you hover over or a '?' button that when clicked gives a pop up window with more information.

**Comment by dagewa** [comment]
This would be to use PHIL help string as a tooltip

**Comment by dagewa** [comment]
Essentially #89 duplicates this.
