### ISSUE TITLE
Does not work with Eiger files

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI#31]
Because template= used; Eiger files do not use templates as such

**Comment by graeme-winter** [comment]
Example in /dls/tmp/gw56/eiger

**Comment by graeme-winter** [comment]
(dials.import ... master.h5 works fine)

**Comment by luisodls** [comment]
updating example path to /dls/mx/data/mx17352/mx17352-107/VMXi-AB0337/well_48/images/image_602.nxs

now DUI works with this data
