### ISSUE TITLE
Listing images takes an age of mankind

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI#4]
I go to a directory and want to select some images... I wait

and wait

several minutes looking at 

<img width="1920" alt="screen shot 2017-05-25 at 15 20 24" src="https://cloud.githubusercontent.com/assets/1241716/26454093/e70826f8-415d-11e7-9983-0853e6deab55.png">

**Comment by graeme-winter** [comment]
And finally did not actually show all of my images!

<img width="1920" alt="screen shot 2017-05-25 at 15 22 34" src="https://cloud.githubusercontent.com/assets/1241716/26454147/1359c414-415e-11e7-99e0-779191919341.png">

**Comment by dagewa** [comment]
I just tried this with a directory containing ~4400 images and listing was more or less instant. Closing this under the assumption it is fixed (please reopen if still a problem)
