### ISSUE TITLE
Show resolution on image view

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#42]
E.g. hovering over any point should show you the resolution at that point - in the status bar (with x, y, I) would be great.

~Additionally, showing a live 'circle' showing the resolution, where you've hovered over sounded very useful to people in the room - making it easier to see anisotropic reflections was mentioned.~

- [ ] Show resolution in the status bar

**Comment by luisodls** [comment]
First part (status bar) Done

**Comment by dagewa** [comment]
Very nice, please add units (Å) and restrict to 1 d.p.

- [ ] Add units to status bar (Å)
- [ ] Restrict display to 1 decimal place

**Comment by luisodls** [comment]
Done ... and Done, closing now
