### ISSUE TITLE
Clicking retry then run on export causes a crash

### ISSUE THREAD

**Issue by jbeilstenedmands** [ccp4/DUI#43]
If you're on the export node and click retry, it created a new node (and names it export, but it's actually integrate), however if you run it then it tries an integrate run but fails and creates a red integrate node.
A user may do this to try and export the output of the already run integrate with a new output name.
Solution - you shouldn't be able to click retry on export.

**Comment by luisodls** [comment]
Solved ... now in "export" node all runable steps are grayed out
