### ISSUE TITLE
Import not expanding to full dataset

### ISSUE THREAD

**Issue by rjgildea** [ccp4/DUI#46]
Trying to import this dataset:

/dls/mx-scratch/rjgildea/Eiger/hdrmx_medsbio/cbf/P3p09_0.5d_0.05s_12.65keV_bslz4_1_#####.cbf.bz2

Output from terminal - note the "*" is inserted in the incorrect place, not in place of the ##### as it should be:

```
dat.tmpl_str = /dls/mx-scratch/rjgildea/Eiger/hdrmx_medsbio/cbf/P3p09_0.5d_0.05s_12.65keV_bslz4_1_#####.cbf.bz2
1
failed to << check_gray_outs() >>
update_pbar_msg = click << find >> to go ahead, or click << Retry >>
it_index = <PyQt4.QtCore.QModelIndex object at 0x7f521a326aa0>
TreeNavWidget(node_clicked)
command_lst[1] = ['import', '/dls/mx-scratch/rjgildea/Eiger/hdrmx_medsbio/cbf/P3p09_*.5d_0.05s_12.65keV_bslz4_1_00001.cbf.bz2']


full_cmd_lst[1] = ['dials.import', '/dls/mx-scratch/rjgildea/Eiger/hdrmx_medsbio/cbf/P3p09_*.5d_0.05s_12.65keV_bslz4_1_00001.cbf.bz2', 'output.datablock=dials_files/1_datablock.json', 'output.log=dials_files/1_import.log', 'output.debug_log=dials_files/1_import.debug.log']

```

**Comment by dagewa** [comment]
I just tested the version in CCP4 and this is still an issue. It should be an easy fix, so added to the high priority milestone. @luisodls, is this still an issue in the master branch, or just the CCP4 version?

**Comment by dagewa** [comment]
This issue also affects the standard Mosflm [HypF test dataset](http://www.ccp4.ac.uk/autostruct/testdata/mosflm/hg_images.tar). Image names follow the template hg_###.mar1600, but if I select the first image DUI writes the glob like hg_001.mar*

**Comment by ndevenish** [comment]
```from dxtbx.sweep_filenames import template_regex```

**Comment by graeme-winter** [comment]
\o/ code reuse
