### ISSUE TITLE
Replace text in buttons with icons

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#48]
The text, like "|<" in buttons is not visually appealing.
![buttons](https://user-images.githubusercontent.com/11502083/39134107-c296e140-470d-11e8-8532-11e2f9078269.png)
Please replace with suitable icons instead.

**Comment by luisodls** [comment]
done

**Comment by ndevenish** [comment]
In cebd82a970673f93f95c6d24d4372a4e83c04bc1

**Comment by dagewa** [comment]
The unicode media controls do not display on all platforms. We should use graphical icons instead

**Comment by luisodls** [comment]
Done ... again

**Comment by ndevenish** [comment]
230195468dabf3b0add3ae62eaabaf73fb6efa21

**Comment by dagewa** [comment]
Thanks, I can confirm the fix :-)
![Screenshot from 2020-02-24 15-49-17](https://user-images.githubusercontent.com/11502083/75167501-5cc05c80-571d-11ea-9766-c27723073bd4.png)
