### ISSUE TITLE
Video jumping frames

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#54]
This morning, the video function is operating slowly and in fact is skipping frames. I found that each time I start and stop the image video function, it skips an extra image compared to the last time. So for example, I start video on frame 1 and it displays frames 1, 11, 21, 31... Then I click to stop then restart the video at frame 1. Now I get frames 1, 12, 23, 34...

**Comment by dagewa** [comment]
Confirmed this also happens with a fresh DUI instance. Just try starting and stopping the image video a few times.

**Comment by luisodls** [comment]
Done ... fixed in update 7.0.57 of CCP4
