### ISSUE TITLE
cannot add mask

### ISSUE THREAD

**Issue by hqp77592** [ccp4/DUI#6]
would like to add a mask before indexing

Requires:
- [x] drawing tools for circle, rectangle
- [x] drawing tools for polygon
- [x] passing details of the shape drawn to `dials.generate_mask`
- [x] automatic run of `dials.apply_mask` to include the mask in the `datablock.json` or `experiments.json` (see also https://github.com/dials/dials/issues/603)
- [x] display of masked areas by e.g. filling masked shapes with block colour

**Comment by dagewa** [comment]
Requires:
- [ ] drawing tools for circle, rectangle and polygon
- [ ] passing details of the shape drawn to `dials.generate_mask`
- [ ] automatic run of `dials.apply_mask` to include the mask in the `datablock.json` or `experiments.json` (see also https://github.com/dials/dials/issues/603)
- [ ] display of masked areas by e.g. filling masked shapes with block colour

**Comment by luisodls** [comment]
Workaround for workshop: use dials.image_viewer and read in mask.pickle

**Comment by ndevenish** [comment]
Current plan:
- Writing a mask.pickle with image viewer causes the lookup.mask field to be written *if* you are on spotfinding or integration step
- If you run with this, planning to copy mask into run folder and 'remember' this when running e.g. integrate later

**Comment by dagewa** [comment]
As agreed on 11/12/18, we don't want to support the workaround longer than necessary. Focus shifts back to providing native masking tools within DUI's image viewer. `dials.apply_mask` now [accepts experiments as input](https://github.com/dials/dials/commit/293efd3a1190b2cbe602201956ff5b196bdb8ec2) which means there is nothing now holding this up from the DIALS side.

**Comment by luisodls** [comment]
Done after finishing the polygon feature

**Comment by dagewa** [comment]
Good! I'm looking forward to seeing this.
