### ISSUE TITLE
Unit cell and space group options missing from dials.index in DUI

### ISSUE THREAD

**Issue by rjgildea** [ccp4/DUI#62]
These are fairly critical parameters to have, and are a serious shortcoming from the GUI. They should both probably appear on the "basic" tab.

**Comment by dagewa** [comment]
In discussion, what DUI needs is a way to recognise the phil `unit_cell` type and provide a widget with 6 numerical entry boxes. Space group should (for now) provide a text entry box. All unrecognised types should not be removed from the interface, but should default to string.

**Comment by luisodls** [comment]
Done ...

Tested by editing from DUI the following parameters with our "X4_wide" dataset:

indexing {
  known_symmetry {
    space_group = "P 1"
    unit_cell = 39.858 42.481 42.452 89.944 89.89 89.994
  }
  method = fft3d fft1d *real_space_grid_search
}

...

It indexes successfully now.
