### ISSUE TITLE
Reciprocal lattice viewer does not launch

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#74]
On all tutorial machines for the BCA summer school, running the tutorials with dui - none of the reciprocal lattice viewers launch.

dui loaded through `module load ccp4-workshop` Pressing the 'reciprocal lattice viewer' button outputs:
```
 running Popen>>> dials.reciprocal_lattice_viewer dials_files/2_reflections.pickle dials_files/2_datablock.json ,  True <<< 

Hi from QThread(run)  ___________________ Before Loop
_________________________________________ Loop ended
after ...close()
self.kill_my_proc
time to kill 10845
attempting to kill pid #: 10845
```
and no window appears.

**Comment by luisodls** [comment]
cannot reproduce

**Comment by ndevenish** [comment]
I seem to recall this being something to do with timeout/timing and/or process tree stuff - there was a problem with the way processes were launched. I remember this being a problem at the 2018 DLS workshop and I think we fixed it, though I can't find the commit that did so.
