### ISSUE TITLE
Add Diamond and CCP4 logo

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#77]
Also funding statement in a Help --> About menu item (requires Help to exist...)

**Comment by dagewa** [comment]
@luisodls and I talked about adding a splash screen, so I worked on a demo in https://github.com/ccp4/DUI/tree/splash-screen. However, DUI does quite a lot before the `QApplication` is set up, so the splash screen appears pretty late. I don't know if there is an easy way around this.

**Comment by ndevenish** [comment]
The good news is that this is like three lines, but you just need to make the QApplication early; see https://github.com/ndevenish/DUI/commit/dab6ac3b0aa28cdb8adaeede3b73766492dd20d2
```
    splash_img = QPixmap(image_resource_name)
    splash = QSplashScreen(splash_img)
    splash.show()
```

The bad news is that this will need an image....
