### ISSUE TITLE
Not using monospace font on Windows or macOS for log text

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#79]
There should be way to get Qt to select a monospace font on any system

**Comment by graeme-winter** [comment]
Not just windows - same on macOS

**Comment by graeme-winter** [comment]
![Screen Shot 2019-06-05 at 08 00 05](https://user-images.githubusercontent.com/1241716/58942139-17b25f80-8775-11e9-9ca5-1680eff1d276.png)

**Comment by ndevenish** [comment]
This looks like it might be useful: https://stackoverflow.com/a/18897568 - there doesn't seem to have been a truly concise solution until Qt 5.2 (2013).

**Comment by ndevenish** [comment]
This is _also_ still a problem on windows
