### ISSUE TITLE
Image View does not work properly with Mosflm test data

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#80]
DUI's image viewer does not properly display the diffraction images for the famous [HypF test dataset](http://www.ccp4.ac.uk/autostruct/testdata/mosflm/hg_images.tar) used in the iMosflm tutorial.

![dui1](https://user-images.githubusercontent.com/11502083/45948572-6e657800-bff0-11e8-8e1c-0e7e963b9d21.png)

I could not find a way to adjust the palette in order to get anything other than a two-colour image separating the active from inactive areas of the image plate.

**Comment by luisodls** [comment]
If you move the top slider of the contrast menu the image shows, see image.
![image](https://user-images.githubusercontent.com/14178049/45950051-0d40a300-bff6-11e8-8f75-70fc308da707.png)

**Comment by luisodls** [comment]
sorry, I meant "Palette tuning" menu

**Comment by dagewa** [comment]
Ah, I was trying to drag it the wrong way. So put that down to user error. It would be nice if it picked a sensible default contrast though.
