### ISSUE TITLE
Please add resolution limit to integrate simple tab

### ISSUE THREAD

**Issue by dagewa** [ccp4/DUI#81]
As raised at WG2

**Comment by dagewa** [comment]
Currently in advanced tab:

![d_min](https://user-images.githubusercontent.com/11502083/46151833-8e52a100-c267-11e8-8fd7-93a3a9422160.png)

Maybe needs a simpler interface for the simple tab, i.e. `resolution [ ] to [ ]`

**Comment by ndevenish** [comment]
Moved to Thailand milestone for now as I believe was in a 'get this done first' list somewhere

**Comment by luisodls** [comment]
done
