### ISSUE TITLE
Tooltips for description of PHIL parameters

### ISSUE THREAD

**Issue by rober-loxl** [ccp4/DUI#89]
Put boxes with the explanations of each function and suggestion of how to deal with problems and crashes. :)

**Comment by dagewa** [comment]
does this mean "tooltips"?

**Comment by ndevenish** [comment]
I think that mostly covers it, but read more as a 'guided help' e.g. what to do it a process fails, what does "indexing" means. I think maybe #78 covers that part, so I'm going to make this ticket explicitly about the tooltips because I think that's what is mostly asked for.

**Comment by dagewa** [comment]
I started looking at this in [phil_params](https://github.com/ccp4/DUI/tree/phil_params). The tooltips are created from `short_caption` and `help` strings. However this is not quite right as it is likely to result in duplicated information:
![Screenshot from 2020-03-09 19-40-10](https://user-images.githubusercontent.com/11502083/76250831-e6078100-623d-11ea-9b8f-7f587c2bdbd5.png)
I think it would be better to ignore the short captions for now. They are not widely used in DIALS anyway.

For DUI2 I hope the simple parameters tab will be auto-generated as well, at least for arbitrary DIALS commands (standard commands could still have bespoke input). For auto-generated simple parameter tabs we could use `short_caption` as the widget labels.
