### ISSUE TITLE
No way to specify inverse goniometer axis

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#90]
Apparently encountered in Brazil(?) - no way to set this without dropping down to import command line. Probably best as an import option to be quick - but probably quite complementary to setting things like beam centre?

**Comment by dagewa** [comment]
Can't currently check - but I have a feeling this was fixed (as an import option), right?

**Comment by dagewa** [comment]
Yes, confirmed this is fixed at DUI import. No way currently to set after import, but it _should_ be a rare requirement
