### ISSUE TITLE
Refinement parameters should not be 'all' by default

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#91]
At the moment the UI says by default on starting refinement:
```
Beam Fix Parameters         [    all ]
Crystal Fix Parameters      [    all ]
Detector Fix Parameters     [    all ]
Goniometer Fix Parameters   [    all ]
```
This is **explicitly wrong** - @luisodls said that this currently means "use the default" unless you change it but even that's wrong because it means you cannot change a parameter *to* 'all'.

These should either have a `[  default  ]` setting, or default to the actual default setting (in which case `[  None  ]` also needs to be added)

**Comment by dagewa** [comment]
Full access to setting of refinement parameters will be needed for ED work, by CCP4 6 month milestone
