### ISSUE TITLE
After most steps the GUI locks up for a long time silently predicting

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI#92]
Would probably make more sense to either (i) be honest and say "I'm predicting all reflections" ideally with a <cancel> button if you do not need this or (ii) {better} compute the predictions live with DIALS code i.e. when displaying the images with predictions on compute them live by holding the experiment object in memory and using the Reeke method to select reflections for prediction.

Would make the process feel much more responsive.

**Comment by dagewa** [comment]
Some other relevant details in #8

**Comment by graeme-winter** [comment]
@dagewa thank you - if you would like to merge this in and close this ticket is fine by me - did not see any on the first couple of pages which sounded like the right issue...

**Comment by dagewa** [comment]
Summary of that issue: DUI calculates 150 M of data for the image overlay for the 540 images of the BAG training.

**Comment by dagewa** [comment]
Ok, will merge in.

**Comment by ndevenish** [comment]
RE: https://github.com/dials/dials/issues/585 this problem (which is separate from #8) should be better. But it needs to be tested, so reopening for now.

**Comment by dagewa** [comment]
> Also from @graeme-winter, worth investigating issues with a data set like this one:
> /dls/i04/data/2018/mx22768-4/Marco/TestThaumatin/Thau_4/Thau_4_1_####.cbf
> not just BAG training data

**Comment by luisodls** [comment]
Since the last changes in both: dials.predict(faster) and DUI(explicit), now is more clear and fluid for the user. So closing now.
