### ISSUE TITLE
Allow scan range to be explicitly overridden in HDF5

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI#93]
When importing e.g. an Eiger data set it is impossible to "slice" the data set which means you are always computing predictions for the entire set even if you are only processing a few frames. 

You _can_ select a subset for spot finding and indexing but then afterwards it will predict for the whole scan which can take ~ 20 minutes. 

Overriding with import ```scan.image_range``` would do it nicely.

**Comment by ndevenish** [comment]
So this is working for non-hdf5 data but needs to be cross-checked for this case. I *think* that the existing solution should work but this isn't obvious and needs to be tested.

**Comment by graeme-winter** [comment]
Helpful case from Diamond:

/dls/i04/data/2018/cm19645-5/20181214/gw/Eiger/Thaum/thaumatin_10/thaumatin_10_1.nxs

Really needs to be cut down to be used...

**Comment by ndevenish** [comment]
So if trying this I think one could just type ` image_range=1-100` in the filename box on import, before pressing run. This is the way cbf sub-ranges are specified. Yes, I know.

**Comment by dagewa** [comment]
Needs testing
