### ISSUE TITLE
Show reciprocal lattice option does not work on slow NFS link

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI#94]
Spotted in user training yesterday - pressing the "show reciprocal lattice view" button did not work - @ndevenish identified why (race condition on subprocess) but logging here for reference so does not get missed.

**Comment by dagewa** [comment]
We discussed that the next time there is a problem with running sub-processes the answer should probably be "use procrunner".

**Comment by ndevenish** [comment]
Verified that this fixes the issue on the G54 computers, but possibly introduced issue reading spotfinding parameters. 

Also need to test other platforms before confirming.
