### ISSUE TITLE
Colour schemes for overlays

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI#95]
Some users found it hard yesterday to understand what was going on with the overlays - the default colour scheme is not so helpful - compare DIALS showing indexed reflections:

![dials](https://user-images.githubusercontent.com/1241716/49208962-29bfd980-f3b1-11e8-9e2a-0d2352ec2e0e.png)

with DUI showing the same:

![dui](https://user-images.githubusercontent.com/1241716/49208972-2f1d2400-f3b1-11e8-897b-85d87aff91da.png)

**Comment by graeme-winter** [comment]
These are the same data set; with the defaults in both cases, a fair comparison I think.

**Comment by luisodls** [comment]
putting a different overlay colour on each theme
